# Generated by Django 5.0.3 on 2024-03-21 22:07

import django.db.models.deletion
import django_ckeditor_5.fields
import rb_books.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('label', models.CharField(max_length=50, unique=True, verbose_name='Label')),
                ('short_label', models.CharField(blank=True, max_length=50, null=True, verbose_name='Label court')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Public',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom de famille')),
            ],
            options={
                'verbose_name': 'Auteur',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('label', models.CharField(max_length=50, unique=True, verbose_name='Label')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Catégorie',
            },
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Éditeur',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('label', models.CharField(max_length=150, verbose_name='Label')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('rating', models.PositiveIntegerField(unique=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Note',
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('label', models.CharField(max_length=15, unique=True, verbose_name='Label')),
                ('index', models.FloatField(unique=True, verbose_name='Index')),
            ],
            options={
                'verbose_name': 'Tome',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Résumé')),
                ('image', models.ImageField(blank=True, null=True, upload_to=rb_books.utils.dynamic_upload_img_path, verbose_name='Couverture')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Titre')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Prix')),
                ('pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Pages')),
                ('quotation', models.TextField(blank=True, null=True, verbose_name='Citation')),
                ('opinion', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Avis détaillé')),
                ('short_opinion', models.TextField(blank=True, null=True, verbose_name='Avis résumé')),
                ('about', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Au sujet du livre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Date modification')),
                ('published', models.BooleanField(default=False, verbose_name='Publié')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date publication')),
                ('current_reading', models.BooleanField(default=False, verbose_name='En cours de lecture')),
                ('incoming_reading', models.BooleanField(default=False, verbose_name='Lecture à venir')),
                ('audience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rb_books.audience', verbose_name='Public')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rb_books.author', verbose_name='Auteur')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rb_books.category', verbose_name='Catégorie')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rb_books.editor', verbose_name='Éditeur')),
            ],
            options={
                'verbose_name': 'Livre',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('label', models.CharField(max_length=50, unique=True, verbose_name='Label')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('example_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rb_books.book', verbose_name='Livre exemple')),
            ],
            options={
                'verbose_name': 'Genre',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, to='rb_books.genre', verbose_name='Genres'),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rb_books.rating', verbose_name='Note'),
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Résumé')),
                ('image', models.ImageField(blank=True, null=True, upload_to=rb_books.utils.dynamic_upload_img_path, verbose_name='Couverture')),
                ('volumes_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de volumes')),
                ('complete', models.BooleanField(default=False, verbose_name='Collection complète')),
                ('show_title', models.BooleanField(default=True, verbose_name='Afficher le titre')),
                ('audience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rb_books.audience', verbose_name='Public')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rb_books.author', verbose_name='Auteur')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rb_books.category', verbose_name='Catégorie')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rb_books.editor', verbose_name='Éditeur')),
                ('genres', models.ManyToManyField(blank=True, to='rb_books.genre', verbose_name='Genres')),
            ],
            options={
                'verbose_name': 'Saga',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rb_books.series', verbose_name='Saga'),
        ),
        migrations.AddField(
            model_name='book',
            name='volume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rb_books.volume', verbose_name='Volume'),
        ),
    ]
