# Generated by Django 5.0.3 on 2024-03-23 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Illustrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom de famille')),
            ],
            options={
                'verbose_name': 'Illustrateur',
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='series',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='illustrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rb_books.illustrator', verbose_name='Illustrateur'),
        ),
        migrations.AddField(
            model_name='series',
            name='illustrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rb_books.illustrator', verbose_name='Illustrateur'),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(blank=True, to='rb_books.author', verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='series',
            name='author',
            field=models.ManyToManyField(blank=True, to='rb_books.author', verbose_name='Auteur'),
        ),
    ]
