# Generated by Django 5.0.3 on 2024-03-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_books', '0002_illustrator_remove_book_author_remove_series_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='show_title',
        ),
        migrations.AddField(
            model_name='book',
            name='show_series_title',
            field=models.BooleanField(default=True, verbose_name='Afficher titre saga'),
        ),
        migrations.AddField(
            model_name='book',
            name='show_volume',
            field=models.BooleanField(default=True, verbose_name='Afficher tome'),
        ),
    ]
